runtime: python310
#entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

runtime_config:
  python_version: 3

handlers:
 Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto