runtime: python310
entrypoint: gunicorn -b :$PORT main:app
#entrypoint: gunicorn -k uvicorn.workers.UvicornWorker main:app
service: api-mid

runtime_config:
  python_version: 3

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /.*
  script: auto

env_variables:
  INSTANCE_CONNECTION_NAME: vmgc-e-commerce:southamerica-east1:middleware-pgsql
  DB_USER: postgres
  DB_PASS: VnBgPQbYzwa95VDm
  DB_NAME: TelemetriaGC
  